;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("org-capture-last-stored"
  (filename . "~/org/journal/daily/2026/2026-10-06.org")
  (front-context-string . "[2026-10-06 Tue ")
  (rear-context-string . "a\n\n** ✍️ Notes\n\n")
  (position . 306)
  (last-modified 27332 51758 65389 0))
)
